language: r

warnings_are_errors: true

cache: packages

sudo: required

services:
  - docker

before_install:
  - docker pull hrbrmstr/splashttpd
  - docker run -p 5023:5023 -p 8050:8050 -p 8051:8051 -d hrbrmstr/splashttpd
  - docker ps -a

r:
 - oldrel
 - release
 - devel

addons:
  apt:
    packages:
      - xclip
      - libv8-dev

env:
  - DISPLAY=""
  - DISPLAY=:99.0

notifications:
  email:
    - bob@rud.is
  irc:
    channels:
      - "104.236.112.222#builds"
    nick: travisci
