language: r
cache: packages
sudo: required
dist: trusty

services:
  - docker

env:
  global:
    - NOT_CRAN=true

before_install:
  - docker pull scrapinghub/splash:3.2
  - docker run -p 5023:5023 -p 8050:8050 -p 8051:8051 -d scrapinghub/splash:3.2
  - docker ps -a

r:
 - oldrel
 - release
 - devel

after_success:
  - Rscript -e 'covr::codecov()'